//
//  DetailWorker.swift
//  marvel-challenge
//
//  Created by Danilo Henrique on 14/07/20.
//  Copyright (c) 2020 danilo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import UIKit
import CoreData

class DetailWorker {

    func getFavoriteCharacter(withId id: Int, completion: (Result<[FavoriteCharacterEntity], Error>) -> Void) {
        CoreDataManager().get(withId: id, completion: completion)
    }
    
    func requestImage(fromURL url: URL, completion: @escaping (Result<UIImage, Error>) -> Void) {
        URLSession.shared.dataTask(with: url) { (data, response, error) in
            DispatchQueue.main.async {
                if let data = data, let image = UIImage(data: data) {
                    completion(.success(image))
                } else {
                    completion(.failure(error ?? NSError()))
                }
            }
        }.resume()
    }
}
