//
//  FavoritesPresenter.swift
//  marvel-challenge
//
//  Created by Danilo Henrique on 11/07/20.
//  Copyright (c) 2020 danilo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol FavoritesPresentationLogic {
    func presentFavorites(response: Favorites.GetFavorites.Response)
    func presentError()
}

class FavoritesPresenter: FavoritesPresentationLogic {
    
    weak var viewController: FavoritesDisplayLogic?
    
    // MARK: Presentation Logic
    
    func presentFavorites(response: Favorites.GetFavorites.Response) {
        let names = response.favorites.map({$0.name ?? "-"})
        let viewModel = Favorites.GetFavorites.ViewModel(names: names)
        viewController?.displayFavorites(viewModel: viewModel)
    }
    
    func presentError() {
        viewController?.displayError(.database)
    }
}
