//
//  FavoritesWorker.swift
//  marvel-challenge
//
//  Created by Danilo Henrique on 11/07/20.
//  Copyright (c) 2020 danilo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData

class FavoritesWorker {
    
    let coreData = CoreDataManager()
    
    func getFavoriteCharacters(completion: (Result<[FavoriteCharacterEntity], Error>) -> Void) {
        let entityName = String(describing: FavoriteCharacterEntity.self)
        coreData.getAll(entityName: entityName, completion: completion)
    }
    
    func removeCharacterFromFavorite(id: Int, completion: (Error?) -> Void) {
        let entityName = String(describing: FavoriteCharacterEntity.self)
        coreData.get(entityName: entityName, withId: id) { (result) in
            switch result {
            case .success(let favorites):
                removeAll(favorites: favorites)
                completion(nil)
            case .failure(_):
                completion(NSError())
            }
        }
    }
    
    private func getAllFavorites(completion: (Result<[FavoriteCharacterEntity], Error>) -> Void) {
        let entityName = String(describing: FavoriteCharacterEntity.self)
        coreData.getAll(entityName: entityName, completion: completion)
    }
    
    private func removeAll(favorites: [NSManagedObject]) {
        for favorite in favorites {
            coreData.delete(object: favorite, completion: nil)
        }
    }
}
