//
//  FavoritesInteractor.swift
//  marvel-challenge
//
//  Created by Danilo Henrique on 11/07/20.
//  Copyright (c) 2020 danilo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritesBusinessLogic {
    func requestFavorites()
    func removeFavoriteFromDatabase(at indexPath: IndexPath)
}

protocol FavoritesDataStore {
    //var name: String { get set }
}

class FavoritesInteractor: FavoritesBusinessLogic, FavoritesDataStore {
    
    var presenter: FavoritesPresentationLogic?
    var worker: FavoritesWorker? = FavoritesWorker()
    
    // MARK: Variables
    
    var favorites: [FavoriteCharacterEntity] = []
    
    // MARK: Business Logic
    
    func requestFavorites() {
        worker?.getFavoriteCharacters { [weak self] (result) in
            guard let self = self else { return }
            
            switch result {
            case .success(let favorites):
                self.favorites = favorites
                let response = Favorites.GetFavorites.Response(favorites: favorites)
                self.presenter?.presentFavorites(response: response)
            case .failure:
                self.presenter?.presentError()
            }
        }
    }
    
    func removeFavoriteFromDatabase(at indexPath: IndexPath) {
        favorites.remove(at: indexPath.row)
        let id = Int(favorites[indexPath.row].id)
        worker?.removeCharacterFromFavorite(id: id, completion: { [weak self] (error) in
            guard let self = self else { return }
            if error != nil {
                self.presenter?.presentError()
            }
        })
    }
}
