//
//  CharactersPresenter.swift
//  marvel-challenge
//
//  Created by Danilo Henrique on 11/07/20.
//  Copyright (c) 2020 danilo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharactersPresentationLogic {
    func presentCharacters(response: Characters.GetCharacters.Response)
    func presentError(_ error: Characters.Error)
}

class CharactersPresenter: CharactersPresentationLogic {
    
    weak var viewController: CharactersDisplayLogic?
    
    // MARK: Presentation Logic
    
    func presentCharacters(response: Characters.GetCharacters.Response) {
        
        guard let results = response.character.data?.results, !results.isEmpty else {
            viewController?.displayError(.emptyList)
            return
        }
        
        let displayedCharacters = results.map { (character) -> Characters.DisplayedCharacter in
            let name = character.name ?? "-"
            return Characters.DisplayedCharacter(name: name)
        }
        
        let viewModel = Characters.GetCharacters.ViewModel(displayedCharacters: displayedCharacters)
        viewController?.displayCharacters(viewModel: viewModel)
    }
    
    func presentError(_ error: Characters.Error) {
        viewController?.displayError(error)
    }
}
