//
//  CharactersModels.swift
//  marvel-challenge
//
//  Created by Danilo Henrique on 11/07/20.
//  Copyright (c) 2020 danilo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Characters {
    
    // MARK: Use cases
    
    enum GetCharacters {
        struct Response {
            let results: [CharacterModel]
            let favorites: [FavoriteCharacterEntity]
        }
        struct ViewModel {
            var displayedCharacters: [DisplayedCharacter]
        }
    }
    
    enum SearchCharacters {
        struct Request {
            let searchText: String
        }
        struct Response {
            let results: [CharacterModel]
        }
        struct ViewModel {
            let displayedCharacters: [DisplayedCharacter]
        }
    }
    
    enum SaveInFavorite {
        struct Request {
            let indexPath: IndexPath
        }
        struct Response {
            let indexPath: IndexPath
        }
        struct ViewModel {
            let indexPath: IndexPath
        }
    }
    
    struct DisplayedCharacter {
        let name: String
        let isFavorited: Bool
    }
    
    enum Error {
        case emptyList
        case unexpectedError
        case databaseError
        
        var description: String {
            switch self {
            case .emptyList:
                return "Não encontramos nenhum héroi"
            case .unexpectedError:
                return "Um erro inesperado aconteceu"
            case .databaseError:
                return "Um erro inesperado aconteceu no banco de dados"
            }
        }
    }
}
