//
//  CharactersInteractor.swift
//  marvel-challenge
//
//  Created by Danilo Henrique on 11/07/20.
//  Copyright (c) 2020 danilo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharactersBusinessLogic {
    func doSomething(request: Characters.Something.Request)
}

protocol CharactersDataStore {
    //var name: String { get set }
}

class CharactersInteractor: CharactersBusinessLogic, CharactersDataStore {
    
    var presenter: CharactersPresentationLogic?
    var worker: CharactersWorker? = CharactersWorker()
    
    
    // MARK: Business Logic
    
    func doSomething(request: Characters.Something.Request) {
        worker = CharactersWorker()
        worker?.doSomeWork()
        
        let response = Characters.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
