//
//  CharactersPresenter.swift
//  marvel-challenge
//
//  Created by Danilo Henrique on 11/07/20.
//  Copyright (c) 2020 danilo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharactersPresentationLogic
{
  func presentSomething(response: Characters.Something.Response)
}

class CharactersPresenter: CharactersPresentationLogic
{
  weak var viewController: CharactersDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Characters.Something.Response)
  {
    let viewModel = Characters.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
