//
//  CharactersWorker.swift
//  marvel-challenge
//
//  Created by Danilo Henrique on 11/07/20.
//  Copyright (c) 2020 danilo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol CharactersWorkerManager {
    func getCharacters(completion: @escaping (Result<CharacterDataWrapperModel, Error>) -> Void)
}

class CharactersWorker {
    
    let manager: CharactersWorkerManager
    
    init(manager: CharactersWorkerManager) {
        self.manager = manager
    }
    
    func requestCharacters(completion: @escaping (Result<CharacterDataWrapperModel, Error>) -> Void ) {
        manager.getCharacters(completion: completion)
    }
}
